import type {NextPage} from 'next';
import BodySingle from 'dh-marvel/components/layouts/body/single/body-single';
import Head from 'next/head';

const Index: NextPage = () => {
    return (                   
            <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <BodySingle title={"Sample"}>
            </BodySingle>
        </>
    )
}

export default Index;
/*
// <LayoutGeneral title='homePage marvel comics' description='pagina principal marvel comics' keywords='home'>
            //     <Typography component='h1' variant='h1'> marvel studios</Typography>                
            // </LayoutGeneral>   
*/      